CREATE DATABASE IF NOT EXISTS ${DATABASE_STAGE};

DROP TABLE IF EXISTS ${DATABASE_STAGE}.${STAGE_TABLE};

CREATE EXTERNAL TABLE IF NOT EXISTS ${DATABASE_STAGE}.${STAGE_TABLE} ( 
        Region_Code string,
        Region_Name string
    )
COMMENT 'Tabela de Regiao'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '${DELIMITED}'
STORED AS TEXTFILE
location '${HDFS_LOCATION}'
TBLPROPERTIES ("skip.header.line.count"="1");