CREATE DATABASE IF NOT EXISTS ${DATABASE_STAGE};

DROP TABLE IF EXISTS ${DATABASE_STAGE}.${STAGE_TABLE};

CREATE EXTERNAL TABLE IF NOT EXISTS ${DATABASE_STAGE}.${STAGE_TABLE} ( 
        Division string,
        Division_Name string
    )
COMMENT 'Tabela de Divisao'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '${DELIMITED}'
STORED AS TEXTFILE
location '${HDFS_LOCATION}'
TBLPROPERTIES ("skip.header.line.count"="1");